// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract TandaPayErrors {
    // Custom errors for efficient reverts
    error NotInIniOrDef();
    error InvalidMember();
    error InvalidSubGroup();
    error NotReorged();
    error NotInDefOrFra();
    error NotWhitelistWindow();
    error ClaimantNotValidMember();
    error NotValidMember();
    error NotInCovereged();
    error NotClaimSubmittionWindow();
    error ClaimNoOccured();
    error NotDefectWindow();
    error NotPayWindow();
    error NotHandingOver();
    error TimeNotPassed();
    error NotIncluded();
    error NotInSuccessorList();
    error SamePeriod();
    error NeedMoreSuccessor();
    error NotInInjectionWindow();
    error AlreadyAdded();
    error NoClaimOccured();
    error ManuallyCollapsed();
    error NotInManualCollaps();
    error PrevPeriodNotEnded();
    error NotPaidInvalid();
    error AlreadySet();
    error NotRefundWindow();
    error WLCAvailable();
    error AmountZero();
    error NotClaimant();
    error NotWhiteListed();
    error AlreadyClaimed();
    error NotClaimWindow();
    error CoverageFullfilled();
    error DelayInitiated();
    error NotInInitilization();
    error DFNotMet();
    error NotInInDefault();
    error TurningTimePassed();
    error AlreadySubmitted();
    error SGMNotFullfilled();
    error OutOfTheCommunity();
    error NotAssignedYet();
    error NotInAssigned();
    error NotInAssignmentSuccessfull();
    error NoValiddMember();
    error InValidClaim();
    error NotFirstSuccessor();
    error CannotBeZeroAddress();
    error InEmergency();
    error NotInEmergency();
    error EmergencyGracePeriod();
    error InsufficientFunds();
    error CommunityIsCollapsed();
    error CannotEmergencyRefund();
}